# Generated by Django 5.0.4 on 2024-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='time_fame',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
