# Generated by Django 5.0.4 on 2024-05-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_remove_lecture_time_lecture_time_fame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='time_fame',
            new_name='time_frame',
        ),
    ]
