# Generated by Django 5.0.4 on 2024-05-08 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_alter_lecture_lecturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='lecture',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='lecture_attendance',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_app.lecturerattendance'),
        ),
    ]
