# Generated by Django 5.0.4 on 2024-05-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_remove_studentattendance_lecture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='location',
        ),
    ]
