# Generated by Django 5.0.4 on 2024-05-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0007_remove_studentattendance_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='location',
        ),
    ]
