# Generated by Django 5.0.4 on 2024-04-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourses',
            old_name='enrolled',
            new_name='course_details',
        ),
    ]
