# Generated by Django 5.0.4 on 2024-05-15 23:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0001_initial'),
        ('studentManagement', '0002_rename_enrolled_studentcourses_course_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourses',
            unique_together={('student', 'course_details')},
        ),
    ]
